// https://www.jenkins.io/doc/pipeline/tour/hello-world/

pipeline {
    agent { docker { image 'ruby:3.3.0-alpine3.19' } }
    stages {
        stage('build') {
            steps {
                sh 'ruby --version'
            }
        }
    }
}
